### ISSUE TITLE
Adding FSharpLint via nuget results in an error on build

### ISSUE THREAD

**Issue by 7sharp9** [fsprojects/FSharpLint#78] opened 2015-04-17 12:47 UTC
```
Target FSharpLint:
	Task "FSharpLintTask"
		Using task FSharpLintTask from FSharpLint.MSBuildIntegration.FSharpLintTask, FSharpLint.MSBuildIntegration, Version=0.1.16.0, Culture=neutral, PublicKeyToken=null
/Users/dave/code/xamarin/monodevelop/main/external/fsharpbinding/packages/FSharpLint.0.1.16/build/FSharpLint.targets: error : Error executing task FSharpLintTask: Could not load file or assembly 'FSharpLint.Application, Version=0.1.16.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
		Error executing task FSharpLintTask: System.IO.FileNotFoundException: Could not load file or assembly 'FSharpLint.Application, Version=0.1.16.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'FSharpLint.Application, Version=0.1.16.0, Culture=neutral, PublicKeyToken=null'
  at System.AppDomain.Load (System.String assemblyString, System.Security.Policy.Evidence assemblySecurity, Boolean refonly) [0x00000] in <filename unknown>:0 
  at System.AppDomain.Load (System.String assemblyString) [0x00000] in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) System.AppDomain:Load (string)
  at System.Reflection.Assembly.Load (System.String assemblyString) [0x00000] in <filename unknown>:0 
  at <StartupCode$FSharpLint-MSBuildIntegration>.$FSharpLintTask+Execute@40.Invoke (System.Object sender, System.ResolveEventArgs args) [0x00000] in <filename unknown>:0 
  at System.AppDomain.DoAssemblyResolve (System.String name, System.Reflection.Assembly requestingAssembly, Boolean refonly) [0x00000] in <filename unknown>:0 
  at (wrapper managed-to-native) System.Type:internal_from_name (string,bool,bool)
  at System.Type.GetType (System.String typeName) [0x00000] in <filename unknown>:0 
  at System.Runtime.Remoting.ObjRef.get_ServerType () [0x00000] in <filename unknown>:0 
  at System.Runtime.Remoting.RemotingServices.Unmarshal (System.Runtime.Remoting.ObjRef objectRef, Boolean fRefine) [0x00000] in <filename unknown>:0 
  at System.Runtime.Remoting.RemotingServices.Unmarshal (System.Runtime.Remoting.ObjRef objectRef) [0x00000] in <filename unknown>:0 
  at System.Runtime.Remoting.ObjRef.GetRealObject (StreamingContext context) [0x00000] in <filename unknown>:0 
  at System.Runtime.Serialization.ObjectRecord.LoadData (System.Runtime.Serialization.ObjectManager manager, ISurrogateSelector selector, StreamingContext context) [0x00000] in <filename unknown>:0 
  at System.Runtime.Serialization.ObjectManager.DoFixups () [0x00000] in <filename unknown>:0 
  at System.Runtime.Serialization.Formatters.Binary.ObjectReader.ReadNextObject (System.IO.BinaryReader reader) [0x00000] in <filename unknown>:0 
  at System.Runtime.Serialization.Formatters.Binary.ObjectReader.ReadObjectGraph (BinaryElement elem, System.IO.BinaryReader reader, Boolean readHeaders, System.Object& result, System.Runtime.Remoting.Messaging.Header[]& headers) [0x00000] in <filename unknown>:0 
  at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.NoCheckDeserialize (System.IO.Stream serializationStream, System.Runtime.Remoting.Messaging.HeaderHandler handler) [0x00000] in <filename unknown>:0 
  at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize (System.IO.Stream serializationStream) [0x00000] in <filename unknown>:0 
  at System.Runtime.Remoting.RemotingServices.DeserializeCallData (System.Byte[] array) [0x00000] in <filename unknown>:0 
  at (wrapper xdomain-invoke) System.AppDomain:CreateInstanceAndUnwrap (string,string)
  at (wrapper remoting-invoke-with-check) System.AppDomain:CreateInstanceAndUnwrap (string,string)
  at FSharpLint.MSBuildIntegration.FSharpLintTask.Execute () [0x00000] in <filename unknown>:0 
  at Microsoft.Build.BuildEngine.TaskEngine.Execute () [0x00000] in <filename unknown>:0 
  at Microsoft.Build.BuildEngine.BuildTask.Execute () [0x00000] in <filename unknown>:0 
		Done building target "FSharpLint" in project "/Users/dave/code/xamarin/monodevelop/main/external/fsharpbinding/FSharp.CompilerBinding/FSharp.CompilerBinding.fsproj" ("/Users/dave/code/xamarin/monodevelop/main/external/fsharpbinding/packages/FSharpLint.0.1.16/build/FSharpLint.targets"); "Build" depends on it.
		Done building target "Build" in project "/Users/dave/code/xamarin/monodevelop/main/external/fsharpbinding/FSharp.CompilerBinding/FSharp.CompilerBinding.fsproj" ("/Library/Frameworks/Mono.framework/Versions/4.0.0/lib/mono/4.5/Microsoft.Common.targets").
		Target perfomance summary:
		     0.342 ms  _DownloadNuGet                                          1 calls
		     1.266 ms  _GetCompileOutputsForClean                              1 calls
		     3.588 ms  _RecordCleanFile                                        1 calls
		     1.683 ms  _ValidateEssentialProperties                            1 calls
		     0.213 ms  AssignLinkMetadata                                      1 calls
		     1.744 ms  AssignTargetPaths                                       1 calls
		     8.251 ms  CheckPrerequisites                                      1 calls
		     1.710 ms  CopyFilesMarkedCopyLocal                                1 calls
		     1.684 ms  CoreCompile                                             1 calls
		     2.403 ms  DeployOutputFiles                                       1 calls
		   155.206 ms  FSharpLint                                              1 calls
		     0.229 ms  GenerateResources                                       1 calls
		     0.357 ms  GenerateSatelliteAssemblies                             1 calls
		     0.733 ms  GenerateTargetFrameworkMonikerAttribute                 1 calls
		     0.978 ms  GetCopyToOutputDirectoryItems                           1 calls
		     1.672 ms  GetFrameworkPaths                                       1 calls
		     7.340 ms  GetReferenceAssemblyPaths                               1 calls
		     4.683 ms  ImplicitlyExpandDesignTimeFacades                       1 calls
		     5.198 ms  PrepareForBuild                                         1 calls
		    31.478 ms  ResolveAssemblyReferences                               1 calls
		     0.383 ms  ResolveProjectReferences                                1 calls
		   403.450 ms  RestorePackages                                         1 calls
		     0.154 ms  SplitProjectReferencesByExistent                        1 calls
		     1.923 ms  SplitResourcesByCulture                                 1 calls
		
		Tasks perfomance summary:
		     0.559 ms  AssignCulture                                           1 calls

---------------------- Done ----------------------

Build: 1 error, 0 warnings
```

**Comment by 7sharp9** [comment] 2015-04-17 12:50
Im on `OSX 10.10.3` with Mono `4.0.0 ((detached/d136b79)`

**Comment by duckmatt** [comment] 2015-04-23 17:03
Thanks for the report, I'm going to be adding an acceptance test for the MSBuild task so that these errors will get caught on CI

**Comment by duckmatt** [comment] 2015-04-30 12:25
Thanks, this has been fixed and a regression test which runs msbuild/xbuild against a project to check it contains some expected lint warnings has been added: `FunctionalTestMSBuildTask`. This will be included on nuget in release 0.2 which will be up once #59 is complete

**Closed by duckmatt** 2015-04-30 12:25 UTC

**Comment by 7sharp9** [comment] 2015-04-30 13:04
It would be really interesting to have this integrated tightly into XS refactoring hints, I wonder if its possible to reuse the core logic?

**Comment by duckmatt** [comment] 2015-04-30 17:05
If the positions of the matched items were added as metadata to the results of analysing the hints then it should be fairly simple for a rearrangement into the proposed solution. The hints are matched analysing the tree from `FSharp.Compiler.Services` so the positions are available - just need to be stored. 

One problem with an automatic refactor is that the hints assume the higher order functions to rearrange are pure, so if there's mutation going on in a function passed to `List.map` (although I'd hope someone wouldn't be doing that :p) then a resulting refactor could introduce a bug

Better integration into other tooling is something that would be great to happen. The MSBuild task adds a few seconds to a build so I can't imagine many people keeping it around, the next thing I'm looking at is speeding it up, but if it could be integrated into tools that already have a parsed AST sitting around it would be far more performant, and not being forced to build to run would also be nice.

**Comment by 7sharp9** [comment] 2015-04-30 17:41
Thats the thing in the F# addin for XS we already have the parse tree and the checker results.  All I would want to do initially would be to place a warning glyph directly in the editor

Automatic refactoring can be tricky.  For a start you would have to recombine the parsetree with any comments in the code, and pay special attention to line feeds and indentation.  Fantomas tried to do this but its far from perfect, especially eating or creating extra line feeds.

If you provided a core engine in nuget form then I could call it by passing in the parsetree and config and collect the results.

**Comment by duckmatt** [comment] 2015-05-01 12:32
That would be great. I'll set up a nuget package #81 with some functions added to the API so that the lint can be called with an AST supplied (currently just takes either a project file, F# file path or F# source and builds the tree itself)

**Comment by duckmatt** [comment] 2015-05-12 12:45
Do you know how third party assemblies referencing assemblies also used in the solution of the F# addin for XS would be handled e.g. `FSharp.Compiler.Services`, do all packages need to be using compatible versions (I've had an issue before caused by an incompatibility between two different versions)?

**Comment by 7sharp9** [comment] 2015-05-12 14:29
I guess if in doubt an assembly redirect, the F# addin normally uses the latest, and only one assembly would be packaged anyway.  When XS is packaged only one version of each assembly is used.

**Comment by 7sharp9** [comment] 2015-05-12 14:30
(Fantomas works ok, thats referenced via nuget too, I think it currently uses an older version of FCS)

**Comment by duckmatt** [comment] 2015-05-14 17:00
Okay great I'll see what happens, I'm hoping to have the package uploaded this weekend

**Comment by duckmatt** [comment] 2015-05-27 12:25
An api package is now on nuget: http://www.nuget.org/packages/FSharpLint.Core/

The main part of the api which includes functions to analyse an existing AST are [exposed in this signature file](https://github.com/fsprojects/FSharpLint/blob/master/src/FSharpLint.Application/Lint.fsi)
